parse-server:
  #build: .
  image: yongjhih/parse-server
  ports:
    - "1337:1337"
  environment:
    DATABASE_URI: $DATABASE_URI
    APP_ID: $APP_ID
    MASTER_KEY: $MASTER_KEY
    PARSE_ROOT: $PARSE_ROOT
  links:
    - mongo
  volumes_from:
    - parse-cloud-code
parse-cloud-code:
  build: cloud/.
  #image: yongjhih/parse-cloud-code
  volumes:
    - /parse/cloud
  command: "ls /parse/cloud"
mongo:
  image: mongo
  ports:
    - "27017:27017"
  volumes_from:
    - mongo-data
#  command: "--smallfiles --logpath=/dev/null --setParameter failIndexKeyTooLong=false --rest --auth"
  command: "--smallfiles --logpath=/dev/null --setParameter failIndexKeyTooLong=false"
# ref. http://www.diogogmt.com/running-mongodb-with-docker-and-compose/
mongo-data:
  image: mongo
  volumes:
    - /data/db
  command: "--break-mongo"
